#!/data/data/com.termux/files/usr/bin/bash
# ============================================================
#  Hồi Ức Ngọc Rồng (HUNR) – Termux Auto Setup v2.0
#  Repo: https://github.com/akah3674-glitch/rem4
#  Hỗ trợ: chạy OFFLINE (local server + APK patch)
# ============================================================

HUNR_DIR="$HOME/hunr-server"
SERVER_JAR="HunrProvision-0.0.1-SNAPSHOT.jar"
DRIVE_SERVER="1qQDKBYGRUxZma7Ax_8z1_v_s54_jAU09"
DB_NAME="hunr_2026"
DB_USER="root"
GAME_PORT=14445
HTTP_PORT=1707

# APK patch constants (PHẢI khớp chính xác byte-for-byte)
APK_OLD_URL="https://hoiucnro.com/server.txt"   # 31 bytes
APK_NEW_URL="http://127.0.0.1:1707/lists.txt"   # 31 bytes ✓ exact match

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; NC='\033[0m'; BOLD='\033[1m'

print_banner() {
    echo -e "${CYAN}"
    echo "╔══════════════════════════════════════════╗"
    echo "║   🐉 Hồi Ức Ngọc Rồng – HUNR Server     ║"
    echo "║   Termux Auto Setup v2.0 (Offline Mode)  ║"
    echo "╚══════════════════════════════════════════╝"
    echo -e "${NC}"
}

print_menu() {
    echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "  ${GREEN}1.${NC} Setup lần đầu (tải + cài đặt hoàn toàn)"
    echo -e "  ${GREEN}2.${NC} Khởi động server"
    echo -e "  ${GREEN}3.${NC} Dừng server"
    echo -e "  ${GREEN}4.${NC} Xem log server (live)"
    echo -e "  ${GREEN}5.${NC} Vào MySQL shell"
    echo -e "  ${GREEN}6.${NC} Thông tin server"
    echo -e "  ${YELLOW}7.${NC} 📱 Patch APK → chạy offline (quan trọng!)"
    echo -e "  ${GREEN}0.${NC} Thoát"
    echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

# ─── Kiểm tra dependencies ───────────────────────────────────
check_deps() {
    local missing=()
    for cmd in java mysqld unzip curl python3; do
        command -v "$cmd" &>/dev/null || missing+=("$cmd")
    done
    if [ ${#missing[@]} -ne 0 ]; then
        echo -e "${YELLOW}Thiếu: ${missing[*]}. Đang cài...${NC}"
        pkg update -y -q
        pkg install -y openjdk-17 mariadb unzip curl python3 2>/dev/null || true
    fi
    # keytool + jarsigner (cần để ký APK)
    command -v keytool &>/dev/null || { pkg install -y openjdk-17 -q 2>/dev/null; }
}

# ─── Tải HUNR_Server.zip từ Google Drive ─────────────────────
download_server() {
    mkdir -p "$HUNR_DIR"
    if [ -f "$HUNR_DIR/$SERVER_JAR" ]; then
        echo -e "${GREEN}✓ Server JAR đã tồn tại, bỏ qua tải${NC}"; return 0
    fi

    local ZIP="$HUNR_DIR/HUNR_Server.zip"
    echo -e "${CYAN}Đang tải HUNR_Server.zip (~1.1GB) từ Google Drive...${NC}"
    echo "  (Có thể mất 10-30 phút tuỳ tốc độ mạng)"

    local URL="https://drive.usercontent.google.com/download?id=${DRIVE_SERVER}&export=download&authuser=0&confirm=t"
    if [ -f "$ZIP" ]; then
        echo "  Tiếp tục tải (resume)..."
        curl -L -A "Mozilla/5.0" -C - "$URL" -o "$ZIP" --progress-bar
    else
        curl -L -A "Mozilla/5.0" "$URL" -o "$ZIP" --progress-bar
    fi

    echo -e "\n${CYAN}Đang giải nén...${NC}"
    unzip -q -o "$ZIP" -d "$HUNR_DIR/tmp_extract" || { echo -e "${RED}Giải nén thất bại!${NC}"; return 1; }

    # Copy JAR
    find "$HUNR_DIR/tmp_extract" -name "*.jar" -exec cp {} "$HUNR_DIR/$SERVER_JAR" \;
    # Copy resources/ và Config/
    find "$HUNR_DIR/tmp_extract" -name "resources" -type d -exec cp -r {} "$HUNR_DIR/" \; 2>/dev/null || true
    find "$HUNR_DIR/tmp_extract" -name "Config" -type d -exec cp -r {} "$HUNR_DIR/" \; 2>/dev/null || true
    # Copy sql/
    find "$HUNR_DIR/tmp_extract" -name "sql" -type d -exec cp -r {} "$HUNR_DIR/" \; 2>/dev/null || true
    # Copy _website nếu có
    find "$HUNR_DIR/tmp_extract" -name "_website" -type d -exec cp -r {} "$HUNR_DIR/" \; 2>/dev/null || true

    rm -rf "$HUNR_DIR/tmp_extract"
    echo -e "${GREEN}✓ Giải nén xong${NC}"
}

# ─── Tạo application.properties ──────────────────────────────
create_config() {
    cat > "$HUNR_DIR/application.properties" << EOF
# HUNR Server – Local Config (auto-generated by hunr_setup.sh)
spring.datasource.url=jdbc:mysql://localhost:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect

server.port=${HTTP_PORT}
game.port=${GAME_PORT}

# Static resources – phục vụ /lists.txt cho APK offline
spring.web.resources.static-locations=file:${HUNR_DIR}/static/,classpath:/static/

logging.level.root=WARN
logging.level.com.ngocrong=INFO
logging.file.name=${HUNR_DIR}/logs/server.log
EOF
    echo -e "${GREEN}✓ Đã tạo application.properties${NC}"
}

# ─── Tạo static/lists.txt (server list cho APK offline) ──────
create_static_files() {
    mkdir -p "$HUNR_DIR/static"
    cat > "$HUNR_DIR/static/lists.txt" << 'EOF'
Local:127.0.0.1:14445:0,0,0
EOF
    echo -e "${GREEN}✓ Đã tạo static/lists.txt (server list cho APK offline)${NC}"
}

# ─── Khởi tạo MySQL ──────────────────────────────────────────
setup_mysql() {
    echo -e "${CYAN}Khởi tạo MariaDB...${NC}"
    mysqld --initialize-insecure --user="$USER" 2>/dev/null || true
    mysqld_safe --user="$USER" &>/dev/null &
    sleep 5

    mysql -u root --connect-timeout=10 -e "
        CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
        GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO 'root'@'localhost';
        FLUSH PRIVILEGES;
    " 2>/dev/null && echo -e "${GREEN}✓ Database '${DB_NAME}' đã sẵn sàng${NC}" || \
        echo -e "${YELLOW}⚠ Không thể kết nối MySQL (có thể đã chạy)${NC}"

    # Chạy SQL bổ sung nếu có
    if ls "$HUNR_DIR/sql/"*.sql &>/dev/null; then
        for f in "$HUNR_DIR/sql/"*.sql; do
            echo "  Đang chạy $f..."
            mysql -u root "$DB_NAME" < "$f" 2>/dev/null || true
        done
        echo -e "${GREEN}✓ SQL setup xong${NC}"
    fi
}

# ─── Tạo start.sh / stop.sh ──────────────────────────────────
create_scripts() {
    cat > "$HUNR_DIR/start.sh" << STARTEOF
#!/data/data/com.termux/files/usr/bin/bash
cd "$HUNR_DIR"
mkdir -p logs

# Bắt đầu MySQL nếu chưa chạy
mysql -u root -e "SELECT 1" &>/dev/null || {
    mysqld_safe --user="\$USER" &>/dev/null &
    sleep 4
}

# Bắt đầu server HUNR
nohup java -jar "$HUNR_DIR/$SERVER_JAR" \\
    --spring.config.location=file:"$HUNR_DIR/application.properties" \\
    > "$HUNR_DIR/logs/server.log" 2>&1 &

echo \$! > "$HUNR_DIR/server.pid"
echo "🐉 HUNR Server đã khởi động! PID=\$(cat "$HUNR_DIR/server.pid")"
echo "   Game port : ${GAME_PORT}"
echo "   HTTP port : ${HTTP_PORT}"
echo "   Server list: http://127.0.0.1:${HTTP_PORT}/lists.txt"
echo "   Log: tail -f $HUNR_DIR/logs/server.log"
STARTEOF

    cat > "$HUNR_DIR/stop.sh" << STOPEOF
#!/data/data/com.termux/files/usr/bin/bash
if [ -f "$HUNR_DIR/server.pid" ]; then
    PID=\$(cat "$HUNR_DIR/server.pid")
    kill "\$PID" 2>/dev/null && echo "✓ Server (PID \$PID) đã dừng" || echo "Server không chạy"
    rm -f "$HUNR_DIR/server.pid"
else
    pkill -f "$SERVER_JAR" 2>/dev/null && echo "✓ Server đã dừng" || echo "Server không chạy"
fi
STOPEOF

    chmod +x "$HUNR_DIR/start.sh" "$HUNR_DIR/stop.sh"
    echo -e "${GREEN}✓ Đã tạo start.sh, stop.sh${NC}"
}

# ─── SETUP LẦN ĐẦU ───────────────────────────────────────────
do_setup() {
    echo -e "\n${BOLD}=== SETUP HUNR SERVER ===${NC}\n"
    check_deps
    download_server
    create_config
    create_static_files
    setup_mysql
    create_scripts

    echo -e "\n${GREEN}${BOLD}✅ SETUP HOÀN TẤT!${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e " Chạy server: ${BOLD}bash $HUNR_DIR/start.sh${NC}"
    echo -e " Patch APK  : ${BOLD}Chọn Menu 7${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}\n"
}

# ─── PATCH APK ───────────────────────────────────────────────
# Thay "https://hoiucnro.com/server.txt" (31 bytes)
# thành "http://127.0.0.1:1707/lists.txt" (31 bytes)
# trong global-metadata.dat của APK Android
# ──────────────────────────────────────────────────────────────
do_patch_apk() {
    echo -e "\n${BOLD}=== PATCH APK – HUNR OFFLINE MODE ===${NC}\n"
    echo -e "${CYAN}Mục đích:${NC}"
    echo "  APK gốc fetch server list từ https://hoiucnro.com/server.txt"
    echo "  Sau patch → fetch từ http://127.0.0.1:1707/lists.txt (local server)"
    echo "  Local server trả về: Local:127.0.0.1:14445:0,0,0"
    echo "  → Game kết nối đến server Termux của bạn!"
    echo ""

    # Tìm APK
    local APK_IN=""
    echo -e "${YELLOW}Tìm APK HUNR trong thiết bị...${NC}"

    # Auto-search thư mục phổ biến
    for search_dir in \
        "$HOME/storage/downloads" \
        "$HOME/storage/shared/Download" \
        "$HOME/Downloads" \
        "/sdcard/Download" \
        "/sdcard/Downloads" \
        "$HOME"; do
        if [ -d "$search_dir" ]; then
            local found
            found=$(find "$search_dir" -maxdepth 3 -name "*.apk" -iname "*hunr*" -o \
                    -name "*.apk" -iname "*hoiuc*" -o \
                    -name "*.apk" -iname "*ngocrong*" 2>/dev/null | head -5)
            if [ -n "$found" ]; then
                echo -e "${GREEN}Tìm thấy APK:${NC}"
                echo "$found" | nl
                APK_IN=$(echo "$found" | head -1)
                break
            fi
        fi
    done

    if [ -z "$APK_IN" ]; then
        echo -e "${YELLOW}Không tìm thấy APK tự động.${NC}"
        echo "Nhập đường dẫn APK gốc HUNR (hoặc Enter để bỏ qua):"
        read -r APK_IN
        [ -z "$APK_IN" ] && { echo "Bỏ qua."; return; }
    else
        echo -e "Dùng: ${BOLD}$APK_IN${NC}"
        echo "Nhấn Enter để xác nhận, hoặc nhập đường dẫn khác:"
        read -r alt_path
        [ -n "$alt_path" ] && APK_IN="$alt_path"
    fi

    [ ! -f "$APK_IN" ] && { echo -e "${RED}File không tồn tại: $APK_IN${NC}"; return 1; }

    local APK_OUT="$HUNR_DIR/HUNR-offline.apk"
    local WORK_DIR="/tmp/hunr_apk_work"

    echo -e "\n${CYAN}Bước 1: Giải nén APK...${NC}"
    rm -rf "$WORK_DIR"
    mkdir -p "$WORK_DIR"
    unzip -q "$APK_IN" -d "$WORK_DIR" || { echo -e "${RED}Lỗi giải nén APK!${NC}"; return 1; }

    # Tìm global-metadata.dat
    local METADATA
    METADATA=$(find "$WORK_DIR" -name "global-metadata.dat" 2>/dev/null | head -1)
    if [ -z "$METADATA" ]; then
        echo -e "${RED}Không tìm thấy global-metadata.dat trong APK!${NC}"
        echo "  APK này có thể không phải IL2CPP build."
        rm -rf "$WORK_DIR"; return 1
    fi
    echo -e "  ${GREEN}✓ Tìm thấy: ${METADATA/$WORK_DIR\//}${NC}"

    echo -e "\n${CYAN}Bước 2: Patch binary (thay URL server list)...${NC}"
    python3 << PYEOF
import sys

metadata_path = "$METADATA"
old_url = b'https://hoiucnro.com/server.txt'   # 31 bytes
new_url = b'http://127.0.0.1:1707/lists.txt'   # 31 bytes – exact match

with open(metadata_path, 'rb') as f:
    data = f.read()

count = data.count(old_url)
if count == 0:
    print(f"  ⚠ Không tìm thấy URL trong metadata!")
    print(f"    Tìm kiếm: {old_url.decode()}")
    print(f"    APK này có thể đã patch, hoặc dùng URL khác.")
    # Thử tìm biến thể
    for alt in [b'hoiucnro.com', b'server.txt', b'hoiuc']:
        pos = data.find(alt)
        if pos != -1:
            ctx = data[max(0,pos-10):pos+40]
            print(f"    Tìm thấy '{alt.decode()}' tại 0x{pos:08x}: {ctx}")
    sys.exit(1)

print(f"  Tìm thấy {count} chỗ cần patch")
patched = data.replace(old_url, new_url)

with open(metadata_path, 'wb') as f:
    f.write(patched)

# Verify
with open(metadata_path, 'rb') as f:
    verify = f.read()
if new_url in verify and old_url not in verify:
    print(f"  ✓ Patch thành công!")
    print(f"    Old: {old_url.decode()}")
    print(f"    New: {new_url.decode()}")
else:
    print("  ✗ Verify thất bại!")
    sys.exit(1)
PYEOF

    [ $? -ne 0 ] && { rm -rf "$WORK_DIR"; return 1; }

    echo -e "\n${CYAN}Bước 3: Đóng gói lại APK...${NC}"
    cd "$WORK_DIR"
    zip -q -r "$APK_OUT.unsigned" . -x "META-INF/*"
    echo -e "  ${GREEN}✓ Đã đóng gói${NC}"

    echo -e "\n${CYAN}Bước 4: Ký APK...${NC}"
    local KEYSTORE="$HUNR_DIR/hunr-debug.keystore"
    if [ ! -f "$KEYSTORE" ]; then
        keytool -genkey -v -keystore "$KEYSTORE" \
            -alias hunr_offline -keyalg RSA -keysize 2048 -validity 36500 \
            -dname "CN=HUNR-Offline,O=Termux,C=VN" \
            -storepass hunr2026 -keypass hunr2026 2>/dev/null
        echo -e "  ${GREEN}✓ Tạo keystore mới${NC}"
    fi

    jarsigner -keystore "$KEYSTORE" \
        -storepass hunr2026 -keypass hunr2026 \
        -sigalg SHA256withRSA -digestalg SHA-256 \
        -verbose:summary \
        "$APK_OUT.unsigned" hunr_offline 2>&1 | tail -3

    mv "$APK_OUT.unsigned" "$APK_OUT"
    rm -rf "$WORK_DIR"

    echo -e "\n${GREEN}${BOLD}✅ PATCH APK HOÀN TẤT!${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e " APK offline: ${BOLD}$APK_OUT${NC}"
    echo -e " File size  : $(du -sh "$APK_OUT" 2>/dev/null | cut -f1)"
    echo -e ""
    echo -e " ${YELLOW}CÁCH CÀI:${NC}"
    echo -e " 1. Copy APK về máy: adb pull $APK_OUT"
    echo -e "    Hoặc: cp $APK_OUT /sdcard/Download/"
    echo -e " 2. Cài APK trên điện thoại (bật Unknown Sources)"
    echo -e " 3. Khởi động HUNR server: bash $HUNR_DIR/start.sh"
    echo -e " 4. Mở game → chọn server 'Local' → chơi offline!"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e ""
    echo -e " ${YELLOW}LƯU Ý:${NC} Server phải ĐANG CHẠY khi mở game"
    echo -e " Kết nối: APK → 127.0.0.1:1707/lists.txt → server list → 127.0.0.1:14445"
}

# ─── MENU ACTIONS ────────────────────────────────────────────
start_server() {
    if [ ! -f "$HUNR_DIR/$SERVER_JAR" ]; then
        echo -e "${RED}Server chưa được setup! Chạy Menu 1 trước.${NC}"; return 1
    fi
    # Đảm bảo MySQL chạy
    mysql -u root --connect-timeout=3 -e "SELECT 1" &>/dev/null || {
        echo -e "${YELLOW}Đang khởi động MySQL...${NC}"
        mysqld_safe --user="$USER" &>/dev/null &
        sleep 4
    }
    mkdir -p "$HUNR_DIR/logs"
    nohup java -jar "$HUNR_DIR/$SERVER_JAR" \
        --spring.config.location=file:"$HUNR_DIR/application.properties" \
        > "$HUNR_DIR/logs/server.log" 2>&1 &
    echo $! > "$HUNR_DIR/server.pid"
    sleep 2
    if kill -0 "$(cat "$HUNR_DIR/server.pid" 2>/dev/null)" 2>/dev/null; then
        echo -e "${GREEN}✓ HUNR Server đang chạy (PID=$(cat "$HUNR_DIR/server.pid"))${NC}"
        echo -e "  Game port   : ${BOLD}$GAME_PORT${NC}"
        echo -e "  HTTP port   : ${BOLD}$HTTP_PORT${NC}"
        echo -e "  Server list : ${BOLD}http://127.0.0.1:$HTTP_PORT/lists.txt${NC}"
    else
        echo -e "${RED}Server khởi động thất bại! Xem log:${NC}"
        tail -20 "$HUNR_DIR/logs/server.log" 2>/dev/null
    fi
}

stop_server() {
    local PID_FILE="$HUNR_DIR/server.pid"
    if [ -f "$PID_FILE" ]; then
        local PID; PID=$(cat "$PID_FILE")
        kill "$PID" 2>/dev/null && echo -e "${GREEN}✓ Server (PID $PID) đã dừng${NC}" || echo "Server không chạy"
        rm -f "$PID_FILE"
    else
        pkill -f "$SERVER_JAR" 2>/dev/null && echo -e "${GREEN}✓ Server đã dừng${NC}" || echo "Server không chạy"
    fi
}

show_log() {
    local LOG="$HUNR_DIR/logs/server.log"
    [ ! -f "$LOG" ] && { echo "Chưa có log."; return; }
    echo -e "${CYAN}Xem log (Ctrl+C để thoát):${NC}"
    tail -f "$LOG"
}

show_info() {
    echo -e "\n${CYAN}${BOLD}=== THÔNG TIN HUNR SERVER ===${NC}"
    echo -e " JAR    : $HUNR_DIR/$SERVER_JAR"
    echo -e " Config : $HUNR_DIR/application.properties"
    echo -e " DB     : $DB_NAME (MySQL root)"
    echo -e " Cổng game  : $GAME_PORT"
    echo -e " Cổng HTTP  : $HTTP_PORT"
    echo -e " Server list: http://127.0.0.1:$HTTP_PORT/lists.txt"
    echo -e " APK offline: $HUNR_DIR/HUNR-offline.apk"
    echo ""
    # Status
    if [ -f "$HUNR_DIR/server.pid" ] && kill -0 "$(cat "$HUNR_DIR/server.pid" 2>/dev/null)" 2>/dev/null; then
        echo -e " Trạng thái: ${GREEN}● ĐANG CHẠY${NC} (PID=$(cat "$HUNR_DIR/server.pid"))"
    else
        echo -e " Trạng thái: ${RED}● KHÔNG CHẠY${NC}"
    fi
    # DB status
    mysql -u root --connect-timeout=3 -e "USE $DB_NAME; SHOW TABLES;" 2>/dev/null | head -5 && \
        echo -e " Database  : ${GREEN}● ONLINE${NC}" || \
        echo -e " Database  : ${RED}● OFFLINE${NC}"
    echo ""
}

# ─── MAIN LOOP ───────────────────────────────────────────────
main() {
    print_banner
    while true; do
        print_menu
        echo -n "Chọn [0-7]: "
        read -r choice
        case "$choice" in
            1) do_setup ;;
            2) start_server ;;
            3) stop_server ;;
            4) show_log ;;
            5) mysql -u root "$DB_NAME" 2>/dev/null || mysql -u root 2>/dev/null ;;
            6) show_info ;;
            7) do_patch_apk ;;
            0) echo -e "${GREEN}Thoát. Chúc chơi vui!${NC}"; exit 0 ;;
            *) echo -e "${RED}Lựa chọn không hợp lệ!${NC}" ;;
        esac
        echo ""
    done
}

main "$@"
